config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  # 請依照專案指定規格來設定路由

     root "tweets#index"



      resources :tweets, only: [:index, :create, :show, :edit, :update, :destroy] do
        resources :replies, only: [:index,:create, :edit, :update, :destroy]
        member do
          post :like
          post :unlike
        end


      end

      resources :users, only: [:index, :show, :edit, :update, :destroy] do
        member do
          get :tweets
          get :likes
          get :replies

          get :followings
          get :followers
        end
      end

      resources :followships, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      resources :replies, only: [:create, :edit, :destroy]







     namespace :admin do
       resources :tweets, only: [:index, :destroy]
       resources :users, only: [:index]
       root "tweets#index"
     end

end

app/models/tweet.rb
class Tweet < ApplicationRecord

  validates_length_of :description, maximum: 140
  validates_presence_of :description


  belongs_to :user, counter_cache: true

  has_many :replies, dependent: :destroy

  # has_many :replied_users, through: :replies, source: :user

  has_many :likes, dependent: :destroy

  has_many :liked_users, through: :likes, source: :user


  # def is_replied?(user)
  #   self.replied_users.include?(user)
  # end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  # def like_at(user)
  #    if self.liked_users.include?(user)
  #      like = self.likes.find_by(user_id: user.id)
  #      return like.created_at
  #    else
  #      return "no like"
  #    end
  #  end



end

app/controllers/admin/tweets_controller.rb
class Admin::TweetsController < Admin::BaseController



    def index

      @tweets = Tweet.page(params[:page]).per(30).order(created_at: :desc)

    end

    def destroy
      @tweet = Tweet.find(params[:id])
      @tweet.destroy
      redirect_to admin_root_path
      flash[:alert] = "tweet was deleted"
    end



  private

    def tweet_params
      params.require(:tweet).permit(:name, :description, :avatar)
    end



end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
before_action :set_tweet, only: [:like, :unlike]
# :edit, :update, :destroy,

  def index
    @users = User.order(followers_count: :desc).limit(10) # 基於測試規格，必須講定變數名稱，請用此變數中存放關注人數 Top 10 的使用者資料


    @tweets = Tweet.new
    @tweets = Tweet.page(params[:page]).per(20).order(created_at: :desc)


  end



  def create

    @tweet = current_user.tweets.build(tweet_params)
       if @tweet.save
         flash[:notice] = 'tweet was successfully created'
         redirect_to tweets_path
       else
         flash[:alert] = @tweet.errors.full_messages.to_sentence
         @tweets = Tweet.page(params[:page]).per(20).order(created_at: :desc)
         render :index
       end
  end


    #  def each(&block)
    #    @users.each(&block)
    #  end


  # def edit
  #    unless @user == current_user
  #      redirect_to tweets_user_path(@user)
  #    end
  #  end
  #
  # def update
  #
  #   @tweet.update(tweet_params)
  #   flash[:notice] = "tweet was updated"
  # end


  # def destroy
  #
  #   @tweet_id = params[:id]
  #   if @tweet.user == current_user
  #     @tweet.destroy
  #     redirect_to tweets_user_path(@user)
  #   end
  #   flash[:alert] = "tweet was deleted"
  # end



  def like

    @tweet.likes.create!(user: current_user)
    @tweet.user.liked_tweets_count
    redirect_to tweets_path
  end

  def unlike

    like = Like.where(tweet: @tweet, user: current_user)
    like.destroy_all
    @tweet.user.liked_tweets_count
    redirect_to tweets_path
  end






  private

  def set_tweet
     @tweet = Tweet.find(params[:id])
  end


  def tweet_params
    params.require(:tweet).permit(:description)
  end

end

app/helpers/admin/tweets_helper.rb
module Admin::TweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/admin/tweets/index.html.erb
<div class="container">
   <div class="row">


     <ul class="nav nav-tabs">
        <li role="presentation" class="active">
         <%= link_to 'Tweet', admin_root_path %>
       </li>
        <li role="presentation">
         <%= link_to 'User List', admin_users_path %>
       </li>

     </ul>

   </div>
 </div>

 <br>
 <div class="container">
   <div class="row">


<table class="table table-bordered">
         <thead>
           <tr>
             <th>ID</th>
             <th>Auther</th>
             <th>Tweets</th>

             <th>Replies</th>
             <th>Likes</th>
             <th>Delete</th>
           </tr>
         </thead>


 <tbody>
  <% @tweets.each do |tweet| %>
  <tr>
    <th scope="row"><%= tweet.id %></th>
    <td><%= tweet.user.name %></td>
    <td><%= tweet.description %></td>
    <td>
      <% tweet.replies.each do |reply| %>
       <%= reply.comment %>
       <% end %>
    </td>
    <td><%= tweet.likes.count %></td>

    <td><%= link_to 'Delete', admin_tweets_path(tweet), method: :delete, data: {confirm:"Are you sure?"} %></td>
  </td>
</tr>
<% end %>
</tbody>
</table>




   </div>
 </div>