config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  # 請依照專案指定規格來設定路由

     root "tweets#index"



      resources :tweets, only: [:index, :create, :show, :edit, :update, :destroy] do
        resources :replies, only: [:index,:create, :edit, :update, :destroy]
        member do
          post :like
          post :unlike
        end


      end

      resources :users, only: [:index, :show, :edit, :update, :destroy] do
        member do
          get :tweets
          get :likes
          get :replies

          get :followings
          get :followers
        end
      end

      resources :followships, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      resources :replies, only: [:create, :edit, :destroy]







     namespace :admin do
       resources :tweets, only: [:index, :destroy]
       resources :users, only: [:index]
       root "tweets#index"
     end

end

app/views/shared/_follow_list.html.erb
   <div class="tweets row">
       <h2><%= user_title %></h2>
       <% users.each_with_index do |user, index| %>

        <% if index.odd? %>
          <div class="col-xs-6 follow-item row pull-right">
        <% else %>
          <div class="col-xs-6 follow-item row pull-left">
        <% end %>
           <div class="col-xs-4">
             <%= image_tag @user.avatar, width: "200%"  if @user.avatar? %>
           </div>
          <div class="col-xs-8">
            <%= link_to user.name, tweets_user_path(user) %><br/>
            <%= truncate user.introduction, length: 200 %>
          </div>
          <%= render partial: "shared/followship", locals: { user: user } %>
        </div>
        
      <% end %>
    </div>

app/views/shared/_followship.html.erb
<% if user != current_user %>
    <% if current_user.following?(user) %>

     <%= link_to "Unfollow", followship_path(user), method: :delete, class: "btn btn-default pull-right my-btn" %>
    <% else %>

     <%= link_to "Follow", followships_path(following_id: user), method: :post, class: "btn btn-default pull-right my-btn" %>
    <% end %>
  <% end %>

app/views/shared/_like.html.erb
<% if tweet.is_liked?(current_user) %>
   <%= link_to "UnLike(#{tweet.likes_count})", unlike_tweet_path(tweet), method: :post, id: 'like' %>
 <% else %>
  <%= link_to "Like(#{tweet.likes_count})", like_tweet_path(tweet), method: :post, id: 'like' %>
 <% end %>

 

app/views/shared/_profile.html.erb
<div class="profile">
   <div class="avatar">
     <%= image_tag @user.avatar, size: "200" if @user.avatar? %>
     <p class="user-name"><%= user.name %></p>
     <div class="intro">
       <%= user.introduction %>
   </div>
   <div class="items">
     <div class="link-items">
       <%= link_to "Tweets #{user.tweets.size}", tweets_user_path(user), class: "links links-black" %><br/>
       <%= link_to "Following #{user.followings.count}", followings_user_path(user), class: "links links-black" %><br/>
       <%= link_to "Follower #{user.followers.count}", followers_user_path(user), class: "links links-black" %><br/>
       <%= link_to "like #{user.likes_count}", likes_user_path(user), class: "links links-black" %>
     </div>

    <div class="button">

     <% if user == current_user %>
       <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-lg btn-default my-btn" %>
     <% else %>
       <%= render partial: "shared/followship", locals: { user: user } %>
     <% end %>
    </div>
  </div>

app/views/shared/_reply.html.erb
<div class="col-md-3">
   <%= image_tag @user.avatar, width: "100%"  if @user.avatar? %>
 </div>
 <div class="col-md-9">
    <p>
      <%= reply.user.name %>
      <%= reply.created_at.strftime("%Y-%m-%d, %H:%M") %>
   </p>
   <p><%= simple_format(reply.comment) %></p>
 </div>

app/views/shared/_tweet.html.erb
<div class="tweet-item row">
   <div class="col-md-12">

       <div>
         <p>
        <%= image_tag tweet.user.avatar, width: "20%"  if tweet.user.avatar? %>
          <%= link_to "@#{tweet.user.name}", tweets_user_path(tweet.user) %>
           <%= tweet.created_at.strftime("%Y-%m-%d, %H:%M") %>
         </p>
         <p><%= tweet.description %></p>
      </div>
    </div>
    <div class="col-md-9 col-md-offset-3">

     <%= link_to "Reply(#{tweet.replies_count})", tweet_replies_path(tweet), class: "links" %>
      <%= render partial: "shared/like", locals: {tweet: tweet} %>
    </div>
  </div>