config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  # 請依照專案指定規格來設定路由

     root "tweets#index"



      resources :tweets, only: [:index, :create, :show, :edit, :update, :destroy] do
        resources :replies, only: [:index,:create, :edit, :update, :destroy]
        member do
          post :like
          post :unlike
        end


      end

      resources :users, only: [:index, :show, :edit, :update, :destroy] do
        member do
          get :tweets
          get :likes
          get :replies

          get :followings
          get :followers
        end
      end

      resources :followships, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      resources :replies, only: [:create, :edit, :destroy]







     namespace :admin do
       resources :tweets, only: [:index, :destroy]
       resources :users, only: [:index]
       root "tweets#index"
     end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  # 需要 app/views/devise 裡找到樣板，加上 name 屬性
  # 並參考 Devise 文件自訂表單後通過 Strong Parameters 的方法

  # validates :name, presence: true
  validates_presence_of :name, length: { maximum: 20 }
  # 加上驗證 name 不能重覆 (關鍵字提示: uniqueness)
  validates :name, uniqueness: true

  has_many :tweets, dependent: :restrict_with_error


  has_many :replies, dependent: :destroy
  has_many :replied_tweets, through: :replies, source: :tweets

  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweets


  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user


  def admin?
     self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end

  def liked_tweets_count
    self.liked_tweets_count = self.tweets.joins(:likes).count
    self.save
    # tweets_count = self.tweets.count
    # followings_count = self.followings.count
    # followers_count = self.followers.count
    # likes_count = self.likes_count
    # liked_tweets_count = self.tweets.sum(:likes_count)

  end

  # def liked_tweets.user
  #   liked_tweets.user = self.liked_tweets.user
  # end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  


    def index
      @users = User.page(params[:page]).per(30).order("tweets_count DESC")

    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


before_action :set_user, only: [:tweets, :edit, :update, :likes, :followings, :followers]



  # def index
  #   @users = User.page(params[:page]).per(30).order('created_at DESC')
  #   @tweets= Tweet.page(params[:page]).per(30).order('created_at DESC')
  # end
  #
  # def show
  #   @commented_restaurants = @user.restaurants.uniq
  #   @favorited_restaurants = @user.restaurants
  #   @followings = @user.followings
  #   @followers = @user.followers
  # end



  def tweets
    @tweets = @user.tweets.page(params[:page]).per(10).order(created_at: :desc)
    @users = User.all
  end


  def edit
     unless @user == current_user
       redirect_to tweets_user_path(@user)
     end
   end


   def update

     if @user.update_attributes(user_params)
       redirect_to tweets_user_path(@user)
       flash[:notice] = "Profile was successfully updated"
     else
       render :edit
       flash[:alert] = "Profile was failed to update"
     end
   end


   def likes
     # @likes # 基於測試規格，必須講定變數名稱
     @likes = @user.tweets.joins(:likes).page(params[:page]).per(10).order("likes.created_at desc")
    #  @likes = @user.liked_tweets.page(params[:page]).per(10).order("likes.created_at DESC")
    # @likes = @user.likes.order(created_at: :desc)
    #@likes_tweet = @user.liked_tweets.order('likes.updated_at DESC')
   end


  def followings
    # @followings # 基於測試規格，必須講定變數名稱
    @followings = @user.followings.order('followships.created_at desc')

  end

  def followers
    # @followers # 基於測試規格，必須講定變數名稱
    @followers = @user.followers.order('followships.created_at desc')

  end





     private

     def set_user
        @user = User.find(params[:id])
     end

     def user_params
       params.require(:user).permit(:name, :introduction, :avatar)
     end



end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
   <div class="row">


     <ul class="nav nav-tabs">
        <li role="presentation">
         <%= link_to 'Tweet', admin_root_path %>
       </li>
        <li role="presentation" class="active">
         <%= link_to 'User List', admin_users_path %>
       </li>

     </ul>

   </div>
 </div>

 <br>
 <div class="container">
   <div class="row">


<table class="table table-bordered">
         <thead>
           <tr>
             <th>ID</th>

             <th>User Name</th>
             <th>Tweets</th>
             <th>Followings</th>
             <th>Followers</th>
             <!-- <th>Replies</th> -->
             <th>Tweets get Likes</th>

           </tr>
         </thead>
         <tbody>
           <% @users.each do |user| %>
           <tr>
             <th scope="row"><%= user.id %></th>

             <td><%= user.name %></td>

             <td><%= user.tweets.count %></td>
             <td><%= user.followings.count %></td>
             <td><%= user.followers.count %></td>

             <td><%= user.liked_tweets_count %></td>




             </td>
           </tr>
           <% end %>
         </tbody>
       </table>

       <%= paginate @users %>

          </div>
        </div>