config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  # 請依照專案指定規格來設定路由

     root "tweets#index"



      resources :tweets, only: [:index, :create, :show, :edit, :update, :destroy] do
        resources :replies, only: [:index,:create, :edit, :update, :destroy]
        member do
          post :like
          post :unlike
        end


      end

      resources :users, only: [:index, :show, :edit, :update, :destroy] do
        member do
          get :tweets
          get :likes
          get :replies

          get :followings
          get :followers
        end
      end

      resources :followships, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      resources :replies, only: [:create, :edit, :destroy]







     namespace :admin do
       resources :tweets, only: [:index, :destroy]
       resources :users, only: [:index]
       root "tweets#index"
     end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "LOGO", root_path, class: "navbar-brand" %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav pull-right">
              <% if current_user %>
                <% if current_user.admin? %>
                  <li><%= link_to 'Admin Panel', admin_root_path %></li>
                <% end %>
              <li>
                <%= link_to tweets_user_path(current_user), class: "nav-avatar" do %>
                  <%= image_tag current_user.avatar, size: "50" if current_user.avatar? %>
                <% end %>
              </li>
              <li><%= link_to('Edit Profile', edit_user_path(current_user)) %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

            <% else %>
              <li><%= link_to '註冊', new_user_registration_path %></li>
              <li><%= link_to '登入', new_user_session_path %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>



         <% if flash[:notice] %>
              <div class="container">
                <div class="row">

                   <div class="alert alert-success alert-dismissible" role="alert">
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= notice %>
               </div>
                 </div>
               </div>
               <% end %>

               <% if flash[:alert] %>
               <div class="container">
                 <div class="row">

                   <div class="alert alert-danger alert-dismissible" role="alert">
                   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                   <%= alert %>
                  </div>
                 </div>
               </div>
            <% end %>


          <div class="container">
         <%= yield %>
      </div>

  </body>
</html>